<a href="https://colab.research.google.com/github/raybishun/Pythonic/blob/main/Jupyter%20Notebook/DataStructures_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Data Structures

### Libraries

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


### NDArray

Homogeneus multidimensional array (all elements of the same type, indexed by a tupled of positive integers)

### **Creation of a 1-dimentional ndarray**

**From a list**

In [2]:
a = array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

**From a tuple**

In [8]:
b = array((1.1,2.2,3,3,4))

In [9]:
b

array([1.1, 2.2, 3. , 3. , 4. ])

In [10]:
type(b)

numpy.ndarray

### **Creation of a 2-dimensional ndarray**

In [20]:
a2 = array([  [1, 2, 3],[4, 5, 6]  ])

In [22]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

### **Additional important attributes**

In [23]:
# ndarray.ndim => number of dimensions (aka rank)
a2.ndim

2

In [24]:
# ndarray.shape => tuple that indicates the dimensions of the array
# Size of the array in each dimension (n,m) => n rows and m columns
a2.shape

(2, 3)

In [25]:
# ndarray.size => total number of elements of the array
a2.size

6

In [26]:
# ndarray.dtype => type of elemetns of the array
a2.dtype

dtype('int64')

### **Creation of n-dimensional arrays**

**In way that transforms lists of lists in 2 dimensional array, it can transform list of lists of lists in 3 dimensional ones and so on...**

In [30]:
a4 = array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])

In [31]:
a4

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [32]:
a4.ndim

4

In [33]:
a4.shape

(2, 2, 2, 2)

## Automatic generation of elements

Array filled with zeros

zeros(tuple dimensions) => it will create an array with the dimensions entered in its argument (a tuple)

In [34]:
z = zeros( (4, 5) )

In [35]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Arrays filled with ones**
ones (tuples dimensions) => it will create an array with ones

In [36]:
o = ones((4, 5))

In [37]:
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Array filled with empty elements
empty (duple dimensions) => it will create an array with random content (depending on the state of the memory)

In [38]:
e = empty((2, 3))

In [39]:
e

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [41]:
s = arange(5, 10, 1)

In [42]:
s

array([5, 6, 7, 8, 9])

In [43]:
s2 = linspace(5.5, 10, 20)

In [44]:
s2

array([ 5.5       ,  5.73684211,  5.97368421,  6.21052632,  6.44736842,
        6.68421053,  6.92105263,  7.15789474,  7.39473684,  7.63157895,
        7.86842105,  8.10526316,  8.34210526,  8.57894737,  8.81578947,
        9.05263158,  9.28947368,  9.52631579,  9.76315789, 10.        ])

In [45]:
r = random.random( (2, 3) )

In [46]:
r

array([[0.01774126, 0.75752635, 0.42538717],
       [0.08863529, 0.78813194, 0.0451678 ]])